DROP INDEX IF EXISTS idx_sims_tenant_created;
DROP INDEX IF EXISTS idx_sims_tenant_iccid_trgm;
DROP INDEX IF EXISTS idx_sims_tenant_imsi_trgm;
DROP INDEX IF EXISTS idx_sessions_state;
DROP INDEX IF EXISTS idx_sessions_acct_active;
DROP INDEX IF EXISTS idx_anomalies_tenant_detected;
DROP INDEX IF EXISTS idx_anomalies_tenant_sim_type_active;
DROP INDEX IF EXISTS idx_audit_tenant_id_desc;
DROP EXTENSION IF EXISTS pg_trgm;
